import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Docs Chat Assistant Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "rgba(13,17,23,255)", color: "rgb(217,225,233)"}}>{children}</body>
    </html>
  );
}
